apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wordpress
  name: wp-mysql-deployment
  namespace: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
  
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      containers:
      - image: mysql 
        name: mysql
        env:
        - name: MYSQL_DATABASE
          value: mysql-project
        - name: MYSQL_USER
          value: admin
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_PASSWORD
          value: password
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-persistent-storage
        ports:
        - containerPort: 3306
      volumes: 
      - name: mysql-persistent-storage
        hostPath: 
          path: /data/mysql
