apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress
  name: wp-mysql-svc-clusterip
  namespace: wordpress
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: wordpress
    tier: mysql
